Repository pygamelib/pygamelib, pull requests merged in 2023-10, with the labels that each got.

#221 Add a base widget and layout system.
  .flake8
  Makefile
  docs/source/base.rst
  docs/source/conf.py
  docs/source/constants.rst
  docs/source/gfx_ui.rst
  docs/source/nstatic/custom.css
  docs/source/pygamelib.base.History.rst
  docs/source/pygamelib.gfx.ui.BoxLayout.rst
  docs/source/pygamelib.gfx.ui.Cursor.rst
  docs/source/pygamelib.gfx.ui.FormLayout.rst
  docs/source/pygamelib.gfx.ui.GridLayout.rst
  docs/source/pygamelib.gfx.ui.Layout.rst
  docs/source/pygamelib.gfx.ui.LineInput.rst
  docs/source/pygamelib.gfx.ui.Widget.rst
  pygamelib/base.py
  pygamelib/constants.py
  pygamelib/engine.py
  pygamelib/gfx/core.py
  pygamelib/gfx/ui.py
  tests/test_animation.py
  tests/test_base.py
  tests/test_base_history.py
  tests/test_board.py
  tests/test_gfx_core_color.py
  tests/test_gfx_core_sprixel.py
  tests/test_gfx_ui_base.py
  tests/test_gfx_ui_boxlayout.py
  tests/test_gfx_ui_cursor.py
  tests/test_gfx_ui_gridlayout.py
  tests/test_gfx_ui_layout.py
  tests/test_gfx_ui_lineinput.py
  tests/test_gfx_ui_widget.py
Labels: enhancement, Hacktoberfest, New feature, refactoring, hacktoberfest-accepted, documentation

#233 Update the badges
  .readthedocs.yaml
  README.md
Labels: bug, enhancement, Hacktoberfest

#234 Add missing requirements and update versions.
  .legacy/requirements.txt
  Pipfile
  Pipfile.lock
  pygamelib/board_items.py
Labels: enhancement, hacktoberfest-accepted

#220 Add type hints to actuators.py
  .coveragerc
  pygamelib/actuators.py
  tests/test_actuators.py
Labels: refactoring, hacktoberfest-accepted, documentation

#237 Switch to enums instead of int literals for constants
  docs/source/constants.rst
  pygamelib/actuators.py
  pygamelib/base.py
  pygamelib/board_items.py
  pygamelib/constants.py
  pygamelib/engine.py
  pygamelib/gfx/core.py
  pygamelib/gfx/ui.py
  tests/test_base.py
Labels: enhancement, hacktoberfest-accepted, documentation

#241 Create SECURITY.md
  .github/ISSUE_TEMPLATE/security_report_template.md
  SECURITY.md
Labels: Meta

#242 Cache the board items position vector.
  pygamelib/board_items.py
Labels: enhancement, refactoring, hacktoberfest-accepted
